### ISSUE TITLE
Using a standard data format

### ISSUE THREAD

**Issue by mhmd-azeez** [KosratDAhmad/MyPrayersData#1]
Hi! I have been developing [Bangbezh ](http://bangbezh.com/) for a few years now and I am glad that you've open sourced the prayer times. That's a huge step forward. But I suggest using a standard data format e.g. (json, xml) for storing the data. I am willing to help in converting the files.

**Comment by kosratdev** [comment]
Hi, 

Thank you very much for your suggestion In Sha Allah in the future I will create an api for this purpose.

**Comment by mhmd-azeez** [comment]
Great! please do let me know if there was anything I could help you with
